name: Handle stale issues

on:
  schedule:
    - cron: '37 7 * * *' # Every day at 07:37
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open for 30 days with no activity.'
          close-issue-message: 'Closing this issue due to inactivity.'
